// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnilfcjmxkafomcswgpc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRuaWxmY2pteGthZm9tY3N3Z3BjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMzg3NDMsImV4cCI6MjA2MDgxNDc0M30.e_Zdpa4vfFqlvH3LJ2qJfnqN4Lr50_3QwGLE7HjILHo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);